version: '3.8'

services:
  amslpr:
    build: .
    network_mode: "host"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./config:/app/config
    restart: unless-stopped
    environment:
      - TZ=UTC
      - PYTHONUNBUFFERED=1
      # Add memory limit for Python
      - PYTHONMALLOC=malloc
      # Limit garbage collector
      - PYTHONGC=1
    deploy:
      resources:
        limits:
          # Limit to 2 cores for RPi 4
          cpus: '2'
          # Limit to 1GB for RPi 4 (leaving room for system)
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 256M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health", "||", "exit", "1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    ulimits:
      nofile:
        soft: 32768
        hard: 32768
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
