version: '3.8'

services:
  amslpr-test:
    build:
      context: .
      dockerfile: Dockerfile.test
    cap_add:
      - NET_BIND_SERVICE
      - NET_RAW
    volumes:
      - .:/app
    environment:
      - FLASK_APP=run_server.py
      - FLASK_ENV=development
      - PYTHONPATH=/app
      - HOST=0.0.0.0
      - PORT=5000
      - DEBUG=True
    network_mode: bridge
    ports:
      - "5000:5000"
