version: '2'

services:
  visigate:
    build: .
    ports:
      - "5001:5001"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./config:/app/config
      - ./models:/app/models
    devices:
      # This will be ignored if the device doesn't exist
      - /dev/hailo0:/dev/hailo0
    environment:
      - TZ=UTC
      - PYTHONUNBUFFERED=1
      - HAILO_ENABLED=true
      - PORT=5001
