version: '2'

services:
  amslpr:
    build: .
    ports:
      - "5001:5001"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./config:/app/config
    environment:
      - TZ=UTC
      - PYTHONUNBUFFERED=1
      - HAILO_ENABLED=true
      - PORT=5001
